fieldLayouts:
  603b9d3c-2d02-45d9-9a7d-694307fe06f5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6bbafa39-9928-4dc1-9cc5-a634ab136e97 # Nav Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 261b7487-5f13-4f2f-aa8d-8ae8404da29e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3e515001-ac63-4e85-8eab-2bede81e8f79
        userCondition: null
handle: headerNav
name: 'Header Nav'
sortOrder: 1
