defaultPlacement: end
enableVersioning: true
handle: riders
name: Riders
propagationMethod: all
siteSettings:
  76a75fc6-8c40-4333-989c-011cf6610338: # motoventure
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
