columnSuffix: iygkorcm
contentColumnType: text
fieldGroup: 473654fb-4a7c-43a4-b3de-1d07dc672412 # Home Page
handle: heroTitle
instructions: null
name: 'Hero Title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
