columnSuffix: strsqkap
contentColumnType: text
fieldGroup: 8453e884-4560-4da7-82f8-fa5ade3471ae # Common
handle: seo
instructions: null
name: SEO
searchable: false
settings:
  description: 'Maecenas sed enim ut sem viverra aliquet eget sit amet. Malesuada fames ac turpis egestas integer. Aliquet lectus proin nibh nisl condimentum id venenatis. Amet'
  hideSocial: ''
  robots:
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
  socialImage:
    - '56'
  suffixAsPrefix: null
  title:
    -
      __assoc__:
        -
          - key
          - '1'
        -
          - locked
          - '0'
        -
          - template
          - '{title}'
    -
      __assoc__:
        -
          - key
          - '2'
        -
          - locked
          - '1'
        -
          - template
          - ' | {{ siteName }}'
  titleSuffix: null
translationKeyFormat: null
translationMethod: none
type: ether\seo\fields\SeoField
